project_name: OnMyBlock
dependencies_file_dir: './licenses/'
whitelist:
  - Apache 2.0
  - LGPL
  - LGPLv2.1+
  - MIT
ignore_groups:
  - test
  - development
ignore_dependencies:
  - bson_ext
  - bundler
  - json
  - unicorn
  - unicorn-rails
